#!/usr/bin/env python3
"""PreToolUse hook: refuse a direct write to a generated or vendored file.

Wired for Write|Edit in .claude/settings.example.json. Copy that to
.claude/settings.json to enable it.

Why a hook and not a CLAUDE.md sentence: "edit src/, not viewer.html" is the one
instruction in this repo whose violation is both easy and silent. The edit
appears to work, the viewer even reflects it in the browser, and the change is
destroyed by the next `python build.py` with no error in between. CI catches it
later; this catches it now, and enforcement of a rule that matters should not be
probabilistic.

Reads the PreToolUse payload on stdin and emits a permission decision. Exits 0
even when denying -- the decision is in the JSON, and a crashed hook must never
be able to block legitimate work, so anything unexpected allows.
"""
from __future__ import annotations   # "str | None" below must import on 3.9

import json
import sys
from pathlib import Path

GENERATED = "viewer.html"       # built by build.py from src/ + vendor/
VENDOR_DIR = "vendor"           # upstream libraries, hashed in vendor/SHA256SUMS
VENDOR_METADATA = {"sha256sums", "urls", "network_apis"}   # casefolded names an upgrade must edit

REASON_GENERATED = (
    "viewer.html is generated by build.py and must not be edited directly -- the "
    "next build would silently discard this change, and `python build.py --check` "
    "fails in CI.\n\n"
    "Edit the source instead, then rebuild:\n"
    "  src/app/*.js        viewer behaviour (one shared closure, filename order)\n"
    "  src/ui/viewer.css   styles\n"
    "  src/ui/layout.html  markup\n"
    "  python build.py && python tests/run_checks.py"
)

REASON_VENDOR = (
    "{path} is vendored upstream code, verified against vendor/SHA256SUMS -- an "
    "edit here fails tests/check_invariants.py.\n\n"
    "Patch around the library in src/app/ instead. A deliberate upgrade is its own "
    "change: replace the file, refresh vendor/SHA256SUMS, and update vendor/URLS "
    "and vendor/NETWORK_APIS for each new URL or network API the checks name -- "
    "after reading the code around it. "
    "Expect an API migration (the bundled three.js is an r13x-era build)."
)


def decide(file_path: str) -> str | None:
    """Return a denial reason, or None to stay out of the way."""
    if not file_path:
        return None
    # Windows and macOS paths are case-insensitive, so "Viewer.html" and
    # "VENDOR/three.min.js" name the same files that the lowercase spellings do.
    # Comparing case-sensitively would let either spelling through on the very
    # platform this project targets.
    name = Path(file_path).name.casefold()
    parts = {p.casefold() for p in Path(file_path).parts}
    if name == GENERATED.casefold():
        return REASON_GENERATED
    if VENDOR_DIR.casefold() in parts:
        # A legitimate upgrade has to edit these: SHA256SUMS records the new hashes,
        # URLS and NETWORK_APIS record each new remote URL and network API after it
        # has been reviewed. Blocking one makes the documented upgrade impossible to
        # follow; tests/check_invariants.py asks this function about every file.
        if name in VENDOR_METADATA:
            return None
        return REASON_VENDOR.format(path=Path(file_path).name)
    return None


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0                                    # never block on a bad payload

    tool_input = payload.get("tool_input") or {}
    reason = decide(tool_input.get("file_path") or tool_input.get("path") or "")
    if reason is None:
        return 0

    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
